sudo: false
language: java
script:
  # fail fast
  - set -e
  # fail if templates/generators contain carriage return '\r'
  - /bin/bash ./bin/utils/detect_carriage_return.sh
  # fail if generators contain merge conflicts
  - /bin/bash ./bin/utils/detect_merge_conflict.sh
  # fail if generators contain tab '\t'
  - /bin/bash ./bin/utils/detect_tab_in_java_class.sh
  # run integration tests defined in maven pom.xml
  - ./mvnw clean verify
jdk:
  - openjdk8
after_success:
  - if [ $SONATYPE_USERNAME ] && [ -z $TRAVIS_TAG ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      mvn clean deploy --settings .travis/settings.xml;
      echo "Finished mvn clean deploy for $TRAVIS_BRANCH";
    fi;
branches:
  only:
  - master